In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("movies_imdb.csv")
print(df.shape)
df

(10000, 4)

,Unnamed: 0,title,overview,genres
0,0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"['Drama', 'Crime']"
1,1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","['Drama', 'Crime']"
2,2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"['Drama', 'Crime']"
3,3,Schindler's List,The true story of how businessman Oskar Schind...,"['Drama', 'History', 'War']"
4,4,12 Angry Men,The defense and the prosecution have rested an...,['Drama']
...,...,...,...,...
9995,9995,The Roommate,"When Sara, a young design student from Iowa, a...","['Thriller', 'Drama', 'Horror']"
9996,9996,The Cold Light of Day,After his family is kidnapped during their sai...,"['Action', 'Thriller', 'Mystery']"
9997,9997,Velvet Buzzsaw,Big money artists and mega-collectors pay a hi...,"['Thriller', 'Mystery', 'Horror']"
9998,9998,"I, Frankenstein","200 years after his shocking creation, Dr. Fra...","['Horror', 'Thriller']"
9999,9999,Cold Creek Manor,A family moves from New York into an old mansi...,"['Mystery', 'Thriller']"

In [3]:
df = df.drop(columns = "Unnamed: 0")

In [4]:
df.head()

,title,overview,genres
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"['Drama', 'Crime']"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","['Drama', 'Crime']"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"['Drama', 'Crime']"
3,Schindler's List,The true story of how businessman Oskar Schind...,"['Drama', 'History', 'War']"
4,12 Angry Men,The defense and the prosecution have rested an...,['Drama']

## **Lowercasing**

In [5]:
df['overview'][2]

'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.'

In [6]:
df['overview'][2].lower()

'in the continuing saga of the corleone crime family, a young vito corleone grows up in sicily and in 1910s new york. in the 1950s, michael corleone attempts to expand the family business into las vegas, hollywood and cuba.'

In [7]:
df['overview'] = df['overview'].str.lower()

In [8]:
df.head()

,title,overview,genres
0,The Shawshank Redemption,imprisoned in the 1940s for the double murder ...,"['Drama', 'Crime']"
1,The Godfather,"spanning the years 1945 to 1955, a chronicle o...","['Drama', 'Crime']"
2,The Godfather Part II,in the continuing saga of the corleone crime f...,"['Drama', 'Crime']"
3,Schindler's List,the true story of how businessman oskar schind...,"['Drama', 'History', 'War']"
4,12 Angry Men,the defense and the prosecution have rested an...,['Drama']

## **Removing HTML Tags**

In [9]:
import re
def remove_html_tags(text):
    if not isinstance(text, str):
        return text
    return re.sub(r'<[^>]+>', '', text)

In [10]:
text = "<html><body><p>Movie 1</p> <p>Actor - Aamir Khan</p><p>Click here to watch <a href='https://google.com/'></body></html>"

In [11]:
remove_html_tags(text)

'Movie 1 Actor - Aamir KhanClick here to watch '

In [12]:
df['overview'].apply(remove_html_tags)

0       imprisoned in the 1940s for the double murder ...
1       spanning the years 1945 to 1955, a chronicle o...
2       in the continuing saga of the corleone crime f...
3       the true story of how businessman oskar schind...
4       the defense and the prosecution have rested an...
                              ...
9995    when sara, a young design student from iowa, a...
9996    after his family is kidnapped during their sai...
9997    big money artists and mega-collectors pay a hi...
9998    200 years after his shocking creation, dr. fra...
9999    a family moves from new york into an old mansi...
Name: overview, Length: 10000, dtype: object

## **Removing URL's**

In [13]:
def remove_url(text):
    if not isinstance(text, str):
        return text
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'',text)

In [14]:
df['overview']=df['overview'].apply(remove_url)

In [15]:
df['overview']

0       imprisoned in the 1940s for the double murder ...
1       spanning the years 1945 to 1955, a chronicle o...
2       in the continuing saga of the corleone crime f...
3       the true story of how businessman oskar schind...
4       the defense and the prosecution have rested an...
                              ...
9995    when sara, a young design student from iowa, a...
9996    after his family is kidnapped during their sai...
9997    big money artists and mega-collectors pay a hi...
9998    200 years after his shocking creation, dr. fra...
9999    a family moves from new york into an old mansi...
Name: overview, Length: 10000, dtype: object

## **Removing Punctuation**

In [16]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [17]:
exclude = string.punctuation

In [18]:
def remove_punctuation(text):  # slow function
    for char in exclude:
        text = text.replace(char,'')
    return text

In [19]:
text = "string. with.74 Punctuation?"
start = time.time()
remove_punctuation(text)
time1 = time.time() - start
print(time1)

5.4836273193359375e-05

In [20]:
def remove_punc1(text):   # fast function
    if not isinstance(text, str):
        return text
    return text.translate(str.maketrans('','',exclude))

In [21]:
# start = time.time()
remove_punc1(text)
time2 = time.time() - start
# print(time1)

In [22]:
time1/time2

1.1656184125138765e-05

In [23]:
df['overview']= df['overview'].apply(remove_punc1)
df['overview']

0       imprisoned in the 1940s for the double murder ...
1       spanning the years 1945 to 1955 a chronicle of...
2       in the continuing saga of the corleone crime f...
3       the true story of how businessman oskar schind...
4       the defense and the prosecution have rested an...
                              ...
9995    when sara a young design student from iowa arr...
9996    after his family is kidnapped during their sai...
9997    big money artists and megacollectors pay a hig...
9998    200 years after his shocking creation dr frank...
9999    a family moves from new york into an old mansi...
Name: overview, Length: 10000, dtype: object

## **Correcting Spelling Mistakes**

In [28]:
from textblob import TextBlob

In [29]:
def spelling_mistakes(text):
    if not isinstance(text,str):
        return text
    textBlb = TextBlob(text)
    return textBlb.correct().string

In [31]:
incorrect_text = "noothing just fuucky off yes good good let's doo ita"
print(spelling_mistakes(incorrect_text))

nothing just lucky off yes good good let's do it

In [28]:
df['overview'].apply(spelling_mistakes)

KeyboardInterrupt:

## **Removing Stopwords**

In [24]:
import nltk
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [Errno -3]
[nltk_data]     Temporary failure in name resolution>

False

In [25]:
from nltk.corpus import stopwords
STOP_WORDS = set(stopwords.words('english'))

In [26]:
def remove_stopwords(text):
    if not isinstance(text,str):
        return ""
    
    return " ".join(
        word for word in text.split() if word.lower() not in STOP_WORDS
    )

In [27]:
remove_stopwords('Hello everyone this is Om Codex a Data Science and ML learning enthusiast while learning I try to code and implement the logic as well and everytime I learn new concept I always try to build a end-to-end project from scratch by understanding each of the steps.')

'Hello everyone Om Codex Data Science ML learning enthusiast learning try code implement logic well everytime learn new concept always try build end-to-end project scratch understanding steps.'

In [28]:
df.head()

,title,overview,genres
0,The Shawshank Redemption,imprisoned in the 1940s for the double murder ...,"['Drama', 'Crime']"
1,The Godfather,spanning the years 1945 to 1955 a chronicle of...,"['Drama', 'Crime']"
2,The Godfather Part II,in the continuing saga of the corleone crime f...,"['Drama', 'Crime']"
3,Schindler's List,the true story of how businessman oskar schind...,"['Drama', 'History', 'War']"
4,12 Angry Men,the defense and the prosecution have rested an...,['Drama']

In [29]:
df['overview']= df['overview'].apply(remove_stopwords)
df['overview']

0       imprisoned 1940s double murder wife lover upst...
1       spanning years 1945 1955 chronicle fictional i...
2       continuing saga corleone crime family young vi...
3       true story businessman oskar schindler saved t...
4       defense prosecution rested jury filing jury ro...
                              ...
9995    sara young design student iowa arrives college...
9996    family kidnapped sailing trip spain young wall...
9997    big money artists megacollectors pay high pric...
9998    200 years shocking creation dr frankensteins c...
9999    family moves new york old mansion countryside ...
Name: overview, Length: 10000, dtype: object

## **Removing Emoji If any**

In [30]:
import re
def remove_emoji(text):
    if not isinstance(text,str):
        return ""
    
    emoji_pattern = re.compile("[" u"\U0001F600-\U0001F64F" # EMOTIONS
                                   u"\U0001F300-\U0001F5FF" # SYMBOLS & PICTOGRAPHS
                                   u"\U0001F680-\U0001F6FF" # TRANSPORT & MAP SYMBOLS
                                   u"\U0001F1E0-\U0001F1FF" #FLAGS
                                   u"\U00002702-\U000027B0"
                                   u"\U000024C2-\U0001F251"
                                   "]+",flags = re.UNICODE)
    return emoji_pattern.sub(r'',text)

In [31]:
remove_emoji("Loved the movie 😘😘")

'Loved the movie '

In [32]:
df['overview'] = df['overview'].apply(remove_emoji)
df['overview']

0       imprisoned 1940s double murder wife lover upst...
1       spanning years 1945 1955 chronicle fictional i...
2       continuing saga corleone crime family young vi...
3       true story businessman oskar schindler saved t...
4       defense prosecution rested jury filing jury ro...
                              ...
9995    sara young design student iowa arrives college...
9996    family kidnapped sailing trip spain young wall...
9997    big money artists megacollectors pay high pric...
9998    200 years shocking creation dr frankensteins c...
9999    family moves new york old mansion countryside ...
Name: overview, Length: 10000, dtype: object

## **Tokenization**

In [33]:
# using .split()

# word split
words = "Hii I am Om-Codex."
print(words.split())

# sentence split
sentences = "Hii I am Om-codex. I do Machine Learning & Data Science related works. I am studying in second year BSc-IT"
print(sentences.split('.'))

['Hii', 'I', 'am', 'Om-Codex.']
['Hii I am Om-codex', ' I do Machine Learning & Data Science related works', ' I am studying in second year BSc-IT']

In [34]:
# using regex
words1 = "Hii I am Om-codex!?"
tokens = re.findall("['\w']+",words1)
tokens

['Hii', 'I', 'am', 'Om', 'codex']

In [35]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Error loading punkt: <urlopen error [Errno -3] Temporary
[nltk_data]     failure in name resolution>
[nltk_data] Error loading punkt_tab: <urlopen error [Errno -3]
[nltk_data]     Temporary failure in name resolution>

False

In [36]:
# using NLTK
from nltk.tokenize import word_tokenize, sent_tokenize
print(word_tokenize("Hii I am Om-Codex!"))


sentences = "Hii I am Om-codex. I do Machine Learning & Data Science related works. I am studying in second year BSc-I.T."
print(sent_tokenize(sentences))

['Hii', 'I', 'am', 'Om-Codex', '!']
['Hii I am Om-codex.', 'I do Machine Learning & Data Science related works.', 'I am studying in second year BSc-I.T.']

In [37]:
pip install spacy

Requirement already satisfied: spacy in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (0.21.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (2.2.6)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from spacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.11.12)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: wrapt in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /home/om-codex/ml/ml_env/lib64/python3.11/site-packages (from jinja2->spacy) (2.1.5)
Note: you may need to restart the kernel to use updated packages.

In [38]:
# using spacy

import spacy
nlp = spacy.load('en_core_web_sm')

In [39]:
doc1 = nlp(words)
doc2 = nlp(sentences)
doc3 = nlp("imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker andy dufresne begins a new life at the shawshank prison, where he puts his accounting skills to work for an amoral warden. during his long stretch in prison, dufresne comes to be admired by the other inmates -- including an older prisoner named red -- for his integrity and unquenchable sense of hope")

In [40]:
for token in doc1:
    print(token)

Hii
I
am
Om
-
Codex
.

In [41]:
for token in doc2:
    print(token)

Hii
I
am
Om
-
codex
.
I
do
Machine
Learning
&
Data
Science
related
works
.
I
am
studying
in
second
year
BSc
-
I.T.

In [42]:
for token in doc3:
    print(token)

imprisoned
in
the
1940s
for
the
double
murder
of
his
wife
and
her
lover
,
upstanding
banker
andy
dufresne
begins
a
new
life
at
the
shawshank
prison
,
where
he
puts
his
accounting
skills
to
work
for
an
amoral
warden
.
during
his
long
stretch
in
prison
,
dufresne
comes
to
be
admired
by
the
other
inmates
--
including
an
older
prisoner
named
red
--
for
his
integrity
and
unquenchable
sense
of
hope

In [43]:
docs = []
def apply_spacy(text):
    if not isinstance(text,str):
        return ""
    for t in text.split('.'):
        doc = nlp(t)
        return " ".join(word for word in text.split(" "))

In [44]:
df['overview'].apply(apply_spacy)

0       imprisoned 1940s double murder wife lover upst...
1       spanning years 1945 1955 chronicle fictional i...
2       continuing saga corleone crime family young vi...
3       true story businessman oskar schindler saved t...
4       defense prosecution rested jury filing jury ro...
                              ...
9995    sara young design student iowa arrives college...
9996    family kidnapped sailing trip spain young wall...
9997    big money artists megacollectors pay high pric...
9998    200 years shocking creation dr frankensteins c...
9999    family moves new york old mansion countryside ...
Name: overview, Length: 10000, dtype: object

## **Stemming**

In [113]:
from nltk.stem.porter import PorterStemmer

In [114]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [115]:
sample = "walks walks walking walked"
stem_words(sample)

'walk walk walk walk'

## **Lemmatization**

In [118]:
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Initialize lemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

# Input sentence
sentence = (
    "He was running and eating at same time. "
    "He has bad habit of swimming after playing long hours in the Sun."
)

# Define punctuation
punctuations = "?.,!"

# Tokenize
sentence_words = word_tokenize(sentence)

# Remove punctuation safely
sentence_words = [word for word in sentence_words if word not in punctuations]

# Print header
print("{:20} {:20}".format("Word", "Lemma"))
print("-" * 40)

# Lemmatize and print
for word in sentence_words:
    print("{:20} {:20}".format(word, wordnet_lemmatizer.lemmatize(word,pos = 'v')))

Word                 Lemma
----------------------------------------
He                   He
was                  be
running              run
and                  and
eating               eat
at                   at
same                 same
time                 time
He                   He
has                  have
bad                  bad
habit                habit
of                   of
swimming             swim
after                after
playing              play
long                 long
hours                hours
in                   in
the                  the
Sun                  Sun

### **Total Number Of Corpus:**

In [126]:
corpus = []
for sentences in df['overview']:
    for word in sentences.split(" "):
        corpus.append(word)
print("Total Number Of Corpus: ",len(corpus))

Total Number Of Corpus:  257521

### **Total Number Of Vocabulary(Unique words)**

In [134]:
vocabulary = []
for sentences in df['overview']:
    for word in sentences.split(" "):
        if word not in vocabulary:
            vocabulary.append(word)
print(len(vocabulary))

31248

In [135]:
print(vocabulary)

['imprisoned', '1940s', 'double', 'murder', 'wife', 'lover', 'upstanding', 'banker', 'andy', 'dufresne', 'begins', 'new', 'life', 'shawshank', 'prison', 'puts', 'accounting', 'skills', 'work', 'amoral', 'warden', 'long', 'stretch', 'comes', 'admired', 'inmates', 'including', 'older', 'prisoner', 'named', 'red', 'integrity', 'unquenchable', 'sense', 'hope', 'spanning', 'years', '1945', '1955', 'chronicle', 'fictional', 'italianamerican', 'corleone', 'crime', 'family', 'organized', 'patriarch', 'vito', 'barely', 'survives', 'attempt', 'youngest', 'son', 'michael', 'steps', 'take', 'care', 'wouldbe', 'killers', 'launching', 'campaign', 'bloody', 'revenge', 'continuing', 'saga', 'young', 'grows', 'sicily', '1910s', 'york', '1950s', 'attempts', 'expand', 'business', 'las', 'vegas', 'hollywood', 'cuba', 'true', 'story', 'businessman', 'oskar', 'schindler', 'saved', 'thousand', 'jewish', 'lives', 'nazis', 'worked', 'slaves', 'factory', 'world', 'war', 'ii', 'defense', 'prosecution', 'rested', 'jury', 'filing', 'room', 'decide', 'spanishamerican', 'guilty', 'innocent', 'murdering', 'father', 'open', 'shut', 'case', 'soon', 'becomes', 'minidrama', 'jurors', 'prejudices', 'preconceptions', 'trial', 'accused', 'girl', 'chihiro', 'trapped', 'strange', 'spirits', 'parents', 'undergo', 'mysterious', 'transformation', 'must', 'call', 'upon', 'courage', 'never', 'knew', 'free', 'batman', 'raises', 'stakes', 'help', 'lt', 'jim', 'gordon', 'district', 'attorney', 'harvey', 'dent', 'sets', 'dismantle', 'remaining', 'criminal', 'organizations', 'plague', 'streets', 'partnership', 'proves', 'effective', 'find', 'prey', 'reign', 'chaos', 'unleashed', 'rising', 'mastermind', 'known', 'terrified', 'citizens', 'gotham', 'joker', 'raj', 'rich', 'carefree', 'happygolucky', 'second', 'generation', 'nri', 'simran', 'daughter', 'chaudhary', 'baldev', 'singh', 'spite', 'strict', 'adherence', 'indian', 'values', 'left', 'india', 'married', 'childhood', 'fiancé', 'leaves', 'mission', 'hands', 'claim', 'lady', 'love', 'noses', 'whole', 'thus', 'supernatural', 'tale', 'set', 'death', 'row', 'southern', 'gentle', 'giant', 'john', 'coffey', 'possesses', 'power', 'heal', 'peoples', 'ailments', 'cell', 'blocks', 'head', 'guard', 'paul', 'edgecomb', 'recognizes', 'coffeys', 'miraculous', 'gift', 'tries', 'desperately', 'stave', 'condemned', 'mans', 'execution', 'unemployed', 'kitaeks', 'takes', 'peculiar', 'interest', 'wealthy', 'glamorous', 'parks', 'livelihood', 'get', 'entangled', 'unexpected', 'incident', 'armies', 'mass', 'final', 'battle', 'fate', 'worldand', 'powerful', 'ancient', 'forces', 'light', 'dark', 'compete', 'determine', 'outcomeone', 'member', 'fellowship', 'ring', 'revealed', 'noble', 'heir', 'throne', 'kings', 'men', 'yet', 'sole', 'triumph', 'evil', 'lies', 'brave', 'hobbit', 'frodo', 'accompanied', 'loyal', 'friend', 'sam', 'hideous', 'wretched', 'gollum', 'ventures', 'deep', 'heart', 'mordor', 'seemingly', 'impossible', 'quest', 'destroy', 'power\u200b', 'burgerloving', 'hit', 'man', 'philosophical', 'partner', 'drugaddled', 'gangsters', 'moll', 'washedup', 'boxer', 'converge', 'sprawling', 'comedic', 'caper', 'adventures', 'unfurl', 'three', 'stories', 'ingeniously', 'trip', 'back', 'forth', 'time', 'high', 'schoolers', 'mitsuha', 'taki', 'complete', 'strangers', 'living', 'separate', 'one', 'night', 'suddenly', 'switch', 'places', 'wakes', 'taki’s', 'body', 'bizarre', 'occurrence', 'continues', 'happen', 'randomly', 'two', 'adjust', 'around', 'civil', 'rages', 'union', 'confederacy', '–', 'quiet', 'loner', 'ruthless', 'hitman', 'mexican', 'bandit', 'comb', 'american', 'southwest', 'search', 'strongbox', 'containing', '200000', 'stolen', 'gold', 'group', 'explorers', 'make', 'use', 'newly', 'discovered', 'wormhole', 'surpass', 'limitations', 'human', 'space', 'travel', 'conquer', 'vast', 'distances', 'involved', 'interstellar', 'voyage', 'low', 'iq', 'accomplished', 'great', 'things', 'present', 'significant', 'historic', 'events—in', 'far', 'exceeding', 'anyone', 'imagined', 'could', 'despite', 'achieved', 'eludes', 'samurai', 'answers', 'villages', 'request', 'protection', 'falls', 'hard', 'times', 'town', 'needs', 'bandits', 'gathers', 'six', 'others', 'teach', 'people', 'defend', 'villagers', 'provide', 'soldiers', 'food', 'henry', 'hill', 'halfirish', 'halfsicilian', 'brooklyn', 'kid', 'adopted', 'neighbourhood', 'early', 'age', 'climbs', 'ranks', 'mafia', 'guidance', 'jimmy', 'conway', 'months', '14yearold', 'seita', 'sister', 'setsuko', 'orphaned', 'mother', 'killed', 'air', 'raid', 'kobe', 'japan', 'falling', 'aunt', 'move', 'abandoned', 'bomb', 'shelter', 'surviving', 'relatives', 'emergency', 'rations', 'depleted', 'struggle', 'survive', 'touching', 'italian', 'book', 'seller', 'ancestry', 'little', 'fairy', 'creative', 'happy', 'would', 'come', 'abrupt', 'halt', 'entire', 'deported', 'concentration', 'camp', 'locked', 'convince', 'thing', 'game', 'tickingtimebomb', 'insomniac', 'slippery', 'soap', 'salesman', 'channel', 'primal', 'male', 'aggression', 'shocking', 'form', 'therapy', 'concept', 'catches', 'underground', 'fight', 'clubs', 'forming', 'every', 'eccentric', 'gets', 'way', 'ignites', 'outofcontrol', 'spiral', 'toward', 'oblivion', 'downonhisluck', 'veteran', 'tsugumo', 'hanshirō', 'enters', 'courtyard', 'prosperous', 'house', 'iyi', 'hopes', 'place', 'commit', 'seppuku—and', 'worthy', 'deliver', 'coup', 'de', 'grâce', 'suicide', 'ritual', 'senior', 'counselor', 'clan', 'questions', 'ronin’s', 'resolve', 'suspecting', 'seeking', 'charity', 'rather', 'honorable', 'end', 'follows', 'pair', 'interlocking', 'lay', 'bare', 'difference', 'honor', 'respect', 'promises', 'examine', 'legendary', 'foundations', 'code', 'filmmaker', 'recalls', 'fell', 'movies', 'theater', 'formed', 'friendship', 'theaters', 'projectionist', 'baggins', 'inheriting', 'uncle', 'bilbo', 'leave', 'home', 'order', 'keep', 'creator', 'along', 'protect', 'ringbearer', 'sure', 'arrives', 'destination', 'mt', 'doom', 'destroyed', 'povertystricken', 'favelas', 'rio', 'janeiro', '1970s', 'choose', 'different', 'paths', 'rocket', 'budding', 'photographer', 'documents', 'increasing', 'drugrelated', 'violence', 'neighborhood', 'josé', '“zé”', 'pequeno', 'ambitious', 'drug', 'dealer', 'diving', 'dangerous', 'abusive', 'husband', 'matilde', 'finds', 'best', 'miguel', 'insecure', 'disoriented', 'neighbor', 'lively', 'joão', 'grilo', 'sly', 'chicó', 'poor', 'guys', 'hinterland', 'cheat', 'bunch', 'small', 'northeastern', 'brazil', 'die', 'judged', 'christ', 'devil', 'virgin', 'mary', 'admitted', 'paradise', 'larcenous', 'real', 'estate', 'clerk', 'marion', 'crane', 'goes', 'lam', 'wad', 'cash', 'starting', 'ends', 'notorious', 'bates', 'motel', 'manager', 'norman', 'cares', 'housebound', 'petty', 'fakes', 'insanity', 'serve', 'sentence', 'mental', 'ward', 'leader', 'patients—and', 'enemy', 'cruel', 'domineering', 'nurse', 'runs', 'members', 'continue', 'sacred', 'ringbut', 'destinies', 'lie', 'towersorthanc', 'tower', 'isengard', 'corrupt', 'wizard', 'saruman', 'awaits', 'saurons', 'fortress', 'baraddur', 'within', 'lands', 'trekking', 'gimli', 'legolas', 'aragorn', 'orccaptured', 'merry', 'pippin', 'nefarious', 'orthanc', 'intriguing', 'sinful', 'exploration', 'seduction', 'forbidden', 'redemption', 'gabriels', 'inferno', 'captivating', 'wildly', 'passionate', 'escape', 'personal', 'hell', 'earn', 'impossibleforgiveness', '8yearold', 'sowon', 'narrowly', 'brutal', 'sexual', 'assault', 'labors', 'coping', 'rage', 'grief', 'former', 'prohibitionera', 'gangster', 'returns', 'lower', 'east', 'side', 'manhattan', 'thirty', 'later', 'confront', 'ghosts', 'regrets', 'old', 'struggling', 'juggling', 'school', 'teenager', 'miles', 'morales', 'unexpectedly', 'bitten', 'radioactive', 'spider', 'develops', 'unfathomable', 'powers', 'like', 'spiderman', 'wrestling', 'implications', 'abilities', 'discovers', 'super', 'collider', 'created', 'madman', 'wilson', 'kingpin', 'fisk', 'causing', 'across', 'spiderverse', 'inadvertently', 'transported', 'dimension', 'epic', 'luke', 'skywalker', 'defeating', 'galactic', 'empire', 'learns', 'ways', 'jedi', 'aging', 'master', 'yoda', 'darth', 'vader', 'determined', 'ever', 'capture', 'meanwhile', 'rebel', 'princess', 'leia', 'cocky', 'han', 'solo', 'chewbacca', 'droids', 'c3po', 'r2d2', 'thrown', 'various', 'stages', 'betrayal', 'despair', 'sophie', 'milliner', 'turned', 'elderly', 'woman', 'witch', 'shop', 'curses', 'encounters', 'howl', 'caught', 'resistance', 'fighting', 'king', 'shouya', 'ishida', 'starts', 'bullying', 'class', 'shouko', 'nishimiya', 'deaf', 'teasing', 'rest', 'turn', 'lack', 'compassion', 'elementary', 'speak', 'wiser', 'tormented', 'past', 'behaviour', 'decides', 'see', 'wants', 'atone', 'sins', 'already', 'late', 'pianist', 'władysław', 'szpilmans', 'experiences', 'warsaw', 'nazi', 'occupation', 'jews', 'city', 'forced', 'ghetto', 'szpilman', 'playing', 'café', '1942', 'stays', 'behind', 'works', 'laborer', 'eventually', 'hiding', 'ruins', 'wartorn', 'homicide', 'detectives', 'desperate', 'hunt', 'serial', 'killer', 'whose', 'crimes', 'based', 'seven', 'deadly', 'haunting', 'film', 'viewers', 'tortured', 'remains', 'victim', 'next', 'seasoned', 'det', 'somerset', 'researches', 'sin', 'effort', 'inside', 'mind', 'novice', 'mills', 'scoffs', 'efforts', 'unravel', 'direction', 'instructor', 'talented', 'drummer', 'pursue', 'perfection', 'cost', 'even', 'humanity', 'cobb', 'skilled', 'thief', 'commits', 'corporate', 'espionage', 'infiltrating', 'subconscious', 'targets', 'offered', 'chance', 'regain', 'payment', 'task', 'considered', 'inception', 'implantation', 'another', 'persons', 'idea', 'professor', 'gabriel', 'emerson', 'finally', 'truth', 'julia', 'mitchells', 'identity', 'realization', 'moment', 'done', 'waiting', 'wellrespected', 'dante', 'specialist', 'remember', 'nothing', 'win', 'anothers', 'arms', 'chances', 'start', 'hardened', 'crosses', 'precocious', 'helped', 'angel', 'change', 'hearts', 'holiday', 'season', 'part', 'adaption', 'erotic', 'romance', 'novel', 'written', 'anonymous', 'canadian', 'author', 'pen', 'name', 'sylvain', 'reynard', 'border', 'plagued', 'neglect', 'corruption', 'frustrated', 'teacher', 'unorthodox', 'method', 'break', 'students’', 'apathy', 'unlock', 'curiosity', 'potential', 'perhaps', 'genius', 'wheelchairbound', 'spies', 'neighbors', 'apartment', 'window', 'convinced', 'committed', 'clarice', 'starling', 'top', 'student', 'fbis', 'training', 'academy', 'jack', 'crawford', 'interview', 'dr', 'hannibal', 'lecter', 'brilliant', 'psychiatrist', 'also', 'violent', 'psychopath', 'serving', 'bars', 'acts', 'cannibalism', 'believes', 'may', 'insight', 'attractive', 'bait', 'draw', 'yokohama', 'shoe', 'executive', 'faces', 'wrenching', 'choice', 'kidnappers', 'mistakenly', 'seize', 'chauffeur’s', 'demand', 'ransom', 'anyway', 'reuniting', 'gwen', 'stacy', 'brooklyn’s', 'fulltime', 'friendly', 'catapulted', 'multiverse', 'society', 'team', 'spiderpeople', 'charged', 'protecting', 'multiverses', 'existence', 'heroes', 'clash', 'handle', 'threat', 'pitted', 'spiders', 'save', 'loves', 'derek', 'vineyard', 'paroled', '3', 'killing', 'africanamerican', 'brother', 'danny', 'vineyards', 'narration', 'learn', 'going', 'skinhead', 'white', 'supremacist', 'gang', 'racial', 'throughout', 'la', 'actions', 'greatly', 'influenced', 'reformed', 'fresh', 'severs', 'contact', 'path', 'cat', 'spirit', 'luo', 'xiaoheis', 'deforested', 'humans', 'creatures', 'wing', 'dreams', 'reconquering', 'land', 'say', 'rightfully', 'however', 'run', 'wuxian', 'separates', 'xiaohei', 'go', 'journey', 'learning', 'control', 'well', 'thoughts', 'whether', 'ally', 'ashitaka', 'prince', 'disappearing', 'emishi', 'cursed', 'demonized', 'boar', 'god', 'west', 'cure', 'san', 'forest', 'eboshi', 'trying', 'bring', 'balance', 'conflict', 'eighties', 'marty', 'mcfly', 'accidentally', 'sent', 'disrupting', 'first', 'meeting', 'attracting', 'mothers', 'romantic', 'repair', 'damage', 'history', 'rekindling', 'inventor', 'doc', 'brown', 'return', '1985', 'five', 'lovely', 'girls', 'hate', 'studying', 'hire', 'parttime', 'tutor', 'futaro', 'guides', 'education', 'spent', 'brought', 'closer', 'feelings', 'growing', 'finish', 'third', 'year', 'last', 'festival', 'approaches', 'sights', 'what’s', 'future', 'kanji', 'watanabe', 'middleaged', 'monotonous', 'bureaucratic', 'position', 'decades', 'cancer', 'look', 'meaning', 'shipwreck', 'intelligent', 'robot', 'called', 'roz', 'stranded', 'uninhabited', 'island', 'harsh', 'environment', 'bonds', 'islands', 'animals', 'baby', 'goose', 'devils', 'hunters', 'secret', 'enemies', 'reze', 'stepped', 'denjis', 'deadliest', 'fueled', 'survival', 'knows', 'rules', 'elite', 'oldfashioned', 'boarding', 'england', 'english', 'inspires', 'students', 'convention', 'day', 'courting', 'disdain', 'stern', 'headmaster', 'rihito', 'sajo', 'perfect', 'score', 'entrance', 'exam', 'hikaru', 'kusakabe', 'band', 'popular', 'among', 'crossed', 'started', 'talking', 'practice', 'school’s', 'upcoming', 'chorus', 'meet', 'regularly', 'helps', 'improve', 'singing', 'listen', 'other’s', 'voice', 'harmonize', 'beat', 'together', 'léon', 'earned', 'rep', 'cleaner', 'nextdoor', 'wiped', 'loosecannon', 'dea', 'agent', 'unwilling', 'custodian', '12yearold', 'mathilda', 'mathildas', 'considers', 'following', 'léons', 'footsteps', 'pop', 'star', 'mima', 'quits', 'career', 'actress', 'role', 'detective', 'show', 'handlers', 'collaborators', 'begin', 'turning', 'murdered', 'harboring', 'guilt', 'haunted', 'visions', 'self', 'mimas', 'reality', 'fantasy', 'meld', 'frenzied', 'paranoia', 'boy', 'friendships', 'injustices', '1960s', 'taiwan', 'abroad', 'tsuneo', 'job', 'assisting', 'josee', 'artist', 'imagination', 'beyond', 'wheelchair', 'tide', 'turns', 'push', 'thought', 'possible', 'inspire', 'fit', 'storybook', 'dictator', 'adenoid', 'hynkel', 'barber', 'avoid', 'persecution', 'hynkels', 'regime', 'tells', 'ariel', '21yearold', 'rock', 'prize', 'ten', 'dollars', 'musical', 'contest', 'option', 'money', 'relationship', 'reunite', 'exgirlfriend', 'breaks', 'due', 'finland', 'internship', 'ortega', 'casting', 'although', 'know', 'music', 'diverse', 'opposite', 'personalities', 'moves', 'technological', 'advances', 'changes', 'violet', 'still', 'lost', 'commanding', 'officer', 'partisans', 'bound', 'strong', 'everyday', 'strain', 'bond', 'hack', 'screenwriter', 'writes', 'screenplay', 'silent', 'faded', 'obscurity', 'bumbling', 'tramp', 'desires', 'build', 'thwarted', 'experience', 'habit', 'wrong', 'railroad', 'builders', 'advance', 'unstoppably', 'arizona', 'desert', 'sea', 'jill', 'flagstone', 'intention', 'disneys', '100th', 'anniversary', 'short', 'features', 'mickey', 'mouse', 'corralling', 'gallery', 'disney', 'characters', 'photo', 'favourite', 'generations', 'george', 'bailey', 'giving', 'bedford', 'prevents', 'skinflint', 'mr', 'potter', 'taking', 'georges', 'modest', 'building', 'loan', 'company', 'christmas', 'eve', 'businesss', '8000', 'troubles', 'hostage', 'rescue', 'creates', 'capt', 'guerrero', 'face', 'ambush', 'met', 'quadriplegic', 'aristocrat', 'injured', 'paragliding', 'accident', 'projects', 'seele', 'orders', 'allout', 'attack', 'nerv', 'aiming', 'evas', 'gendo', 'plans', 'instrumentality', 'project', 'shinji', 'pushed', 'limits', 'sanity', 'height', 'vietnam', 'captain', 'benjamin', 'willard', 'officially', 'exist', 'goal', 'locate', 'eliminate', 'green', 'beret', 'colonel', 'walter', 'kurtz', 'leading', 'army', 'illegal', 'guerrilla', 'missions', 'territory', '19', 'isaiah', 'wright', 'basketball', 'video', 'games', 'odds', 'single', 'cynthia', 'given', 'ultimatum', 'step', 'feeling', 'pull', 'friends', 'mom', 'hired', 'moore', 'fitness', 'unaware', 'owner', 'personally', 'impact', 'prayers', 'mentor', 'deal', 'sacrifice', 'selfishness', 'discover', 'might', 'greater', 'purpose', 'hot', 'summer', 'enchanted', 'mountain', 'reside', 'appears', 'cannot', 'touch', 'fear', 'making', 'disappear', 'wondrous', 'adventure', 'beautiful', 'blind', 'flower', 'onandoff', 'allows', 'benefactor', 'suitor', 'defends', 'scapegoats', 'failed', 'offensive', 'occurred', 'french', '1916', 'haruki', 'secretly', 'akihiko', 'roommate', 'violinist', 'ugetsu', 'murata', 'ugetsus', 'clashes', 'forward', 'lion', 'simba', 'eager', 'become', 'pride', 'watchful', 'eye', 'mufasa', 'villainous', 'scar', 'conspires', 'amid', 'tragedy', 'rightful', 'circle', 'separated', 'intellectual', 'disability', 'prove', 'innocence', 'jailed', 'commanders', 'child', 'returning', 'earth', 'imitator', 'pedro', 'infante', 'longer', 'womanizer', 'enter', 'fujisawa', 'sakuta', 'azusagawa', 'blissful', 'days', 'girlfriend', 'upperclassman', 'mai', 'sakurajima', 'interrupted', 'appearance', 'crush', 'shoko', 'makinohara', 'virtuoso', 'piano', 'player', 'aboard', 'ocean', 'liner', 'born', 'raised', 'ship', '1900', 'learned', 'outside', 'interactions', 'passengers', 'setting', 'foot', 'fears', 'willing', 'clue', 'came', 'drugged', '15', 'seeks', 'captors', '17', 'dying', 'give', 'musician', 'zach', 'sobiech', 'spread', 'leaving', 'live', 'limited', 'dream', 'makes', 'album', 'viral', 'phenomenon', 'four', 'hatching', 'plan', 'literally', 'dig', 'jail', 'claude', 'gaspard', 'moved', 'risk', 'share', 'newcomer', 'course', 'prisoners', 'concrete', 'floor', 'using', 'bed', 'post', 'sewer', 'system', 'anything', 'assured', 'classmate', 'diagnosed', 'pancreatic', 'disease', 'average', 'schooler', '22nd', 'century', 'matrix', 'computer', 'hacker', 'joins', 'insurgents', 'computers', 'rule', 'devastating', 'events', 'avengers', 'infinity', 'universe', 'mad', 'titan', 'thanos', 'allies', 'assemble', 'undo', 'restore', 'matter', 'consequences', 'store', 'taylor', 'swift', 'stage', 'dallas', 'reputation', 'stadium', 'tour', 'celebrates', 'monumental', 'memories', 'visual', 'magic', 'continued', 'threats', 'large', 'hero', 'danger', 'emerged', 'cosmic', 'shadows', 'despot', 'intergalactic', 'infamy', 'collect', 'stones', 'artifacts', 'unimaginable', 'inflict', 'twisted', 'everything', 'fought', 'led', 'uncertain', 'selfish', 'postman', 'reclusive', 'toymaker', 'unlikely', 'delivering', 'joy', 'cold', 'tony', 'lip', 'bouncer', '1962', 'drive', 'shirley', 'south', 'african', 'americans', 'alternate', 'accommodations', 'services', 'segregation', 'laws', 'masondixon', 'line', 'relied', 'guide', 'negro', 'motorist', 'roberto', 'shy', 'law', 'rome', 'meets', 'bruno', 'fortyyearold', 'exuberant', 'capricious', 'roman', 'tuscany', 'countries', 'blend', 'daily', 'though', 'pair’s', 'newfound', 'tested', 'seventeenyearold', 'stella', 'spends', 'hospital', 'cystic', 'fibrosis', 'patient', 'full', 'routines', 'boundaries', 'selfcontrol', '—', 'put', 'test', 'impossibly', 'charming', 'teen', 'illness', 'theres', 'instant', 'flirtation', 'restrictions', 'dictate', 'maintain', 'safe', 'distance', 'connection', 'intensifies', 'temptation', 'throw', 'embrace', 'attraction', 'emperor', 'marcus', 'aurelius', 'devious', 'demotes', 'maximus', 'romes', 'capable', 'generals', 'preferred', 'gladiator', 'amusement', 'paying', 'audiences', 'terrifying', 'date', 'attacked', 'zombies', 'released', 'thriller’s', 'success', 'redefined', 'broke', 'barriers', 'became', 'inducted', 'us', 'national', 'registry', 'troops', 'storm', 'beaches', 'normandy', 'brothers', 'dead', 'battlefield', 'fourth', 'lines', 'ranger', 'miller', 'tasked', 'penetrating', 'germanheld', 'bringing', 'offers', 'recent', 'widow', 'raise', 'unpredictable', 'sometimes', 'concert', 'documenting', 'swifts', 'recordbreaking', 'eras', '20232024', 'filmed', 'los', 'angeles', 'shows', 'captures', 'tours', 'representing', 'era', 'showcases', '40', 'songs', 'elaborate', 'productions', 'performance', 'werewolf', 'dies', 'inheritance', 'fathers', 'traits', 'challenge', 'ailing', 'barrister', 'thrust', 'courtroom', 'unusual', 'eventful', 'cases', 'lawyers', 'defending', 'tried', 'socialite', 'invasion', 'village', 'belarus', 'german

## **Bag Of Words**

In [99]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [100]:
bow = cv.fit_transform(df['overview'][:1])

In [101]:
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'imprisoned': 11, '1940s': 0, 'double': 8, 'murder': 18, 'wife': 33, 'lover': 17, 'upstanding': 31, 'banker': 5, 'andy': 4, 'dufresne': 9, 'begins': 6, 'new': 20, 'life': 15, 'shawshank': 27, 'prison': 22, 'puts': 24, 'accounting': 1, 'skills': 28, 'work': 34, 'amoral': 3, 'warden': 32, 'long': 16, 'stretch': 29, 'comes': 7, 'admired': 2, 'inmates': 13, 'including': 12, 'older': 21, 'prisoner': 23, 'named': 19, 'red': 25, 'integrity': 14, 'unquenchable': 30, 'sense': 26, 'hope': 10}
35

In [102]:
print(bow[0].toarray())

[[1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1]]

In [103]:
cv.transform(['It is a thriller movie where thief and his wife were mudured']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

### **n-grams**

In [104]:
cv = CountVectorizer(ngram_range = (1,1))
bow = cv.fit_transform(df['overview'][:1])
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'imprisoned': 11, '1940s': 0, 'double': 8, 'murder': 18, 'wife': 33, 'lover': 17, 'upstanding': 31, 'banker': 5, 'andy': 4, 'dufresne': 9, 'begins': 6, 'new': 20, 'life': 15, 'shawshank': 27, 'prison': 22, 'puts': 24, 'accounting': 1, 'skills': 28, 'work': 34, 'amoral': 3, 'warden': 32, 'long': 16, 'stretch': 29, 'comes': 7, 'admired': 2, 'inmates': 13, 'including': 12, 'older': 21, 'prisoner': 23, 'named': 19, 'red': 25, 'integrity': 14, 'unquenchable': 30, 'sense': 26, 'hope': 10}
35

In [105]:
cv = CountVectorizer(ngram_range = (2,2))
bow = cv.fit_transform(df['overview'][:1])
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'imprisoned 1940s': 11, '1940s double': 0, 'double murder': 8, 'murder wife': 18, 'wife lover': 34, 'lover upstanding': 17, 'upstanding banker': 32, 'banker andy': 5, 'andy dufresne': 4, 'dufresne begins': 9, 'begins new': 6, 'new life': 20, 'life shawshank': 15, 'shawshank prison': 28, 'prison puts': 23, 'puts accounting': 25, 'accounting skills': 1, 'skills work': 29, 'work amoral': 35, 'amoral warden': 3, 'warden long': 33, 'long stretch': 16, 'stretch prison': 30, 'prison dufresne': 22, 'dufresne comes': 10, 'comes admired': 7, 'admired inmates': 2, 'inmates including': 13, 'including older': 12, 'older prisoner': 21, 'prisoner named': 24, 'named red': 19, 'red integrity': 26, 'integrity unquenchable': 14, 'unquenchable sense': 31, 'sense hope': 27}
36

In [106]:
cv = CountVectorizer(ngram_range = (3,3))
bow = cv.fit_transform(df['overview'][:1])
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'imprisoned 1940s double': 11, '1940s double murder': 0, 'double murder wife': 8, 'murder wife lover': 18, 'wife lover upstanding': 33, 'lover upstanding banker': 17, 'upstanding banker andy': 31, 'banker andy dufresne': 5, 'andy dufresne begins': 4, 'dufresne begins new': 9, 'begins new life': 6, 'new life shawshank': 20, 'life shawshank prison': 15, 'shawshank prison puts': 27, 'prison puts accounting': 23, 'puts accounting skills': 25, 'accounting skills work': 1, 'skills work amoral': 28, 'work amoral warden': 34, 'amoral warden long': 3, 'warden long stretch': 32, 'long stretch prison': 16, 'stretch prison dufresne': 29, 'prison dufresne comes': 22, 'dufresne comes admired': 10, 'comes admired inmates': 7, 'admired inmates including': 2, 'inmates including older': 13, 'including older prisoner': 12, 'older prisoner named': 21, 'prisoner named red': 24, 'named red integrity': 19, 'red integrity unquenchable': 26, 'integrity unquenchable sense': 14, 'unquenchable sense hope': 30}
35

In [107]:
cv = CountVectorizer(ngram_range = (1,2))
bow = cv.fit_transform(df['overview'][:1])
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'imprisoned': 22, '1940s': 0, 'double': 16, 'murder': 36, 'wife': 67, 'lover': 34, 'upstanding': 63, 'banker': 10, 'andy': 8, 'dufresne': 18, 'begins': 12, 'new': 40, 'life': 30, 'shawshank': 55, 'prison': 44, 'puts': 49, 'accounting': 2, 'skills': 57, 'work': 69, 'amoral': 6, 'warden': 65, 'long': 32, 'stretch': 59, 'comes': 14, 'admired': 4, 'inmates': 26, 'including': 24, 'older': 42, 'prisoner': 47, 'named': 38, 'red': 51, 'integrity': 28, 'unquenchable': 61, 'sense': 53, 'hope': 21, 'imprisoned 1940s': 23, '1940s double': 1, 'double murder': 17, 'murder wife': 37, 'wife lover': 68, 'lover upstanding': 35, 'upstanding banker': 64, 'banker andy': 11, 'andy dufresne': 9, 'dufresne begins': 19, 'begins new': 13, 'new life': 41, 'life shawshank': 31, 'shawshank prison': 56, 'prison puts': 46, 'puts accounting': 50, 'accounting skills': 3, 'skills work': 58, 'work amoral': 70, 'amoral warden': 7, 'warden long': 66, 'long stretch': 33, 'stretch prison': 60, 'prison dufresne': 45, 'dufresne comes': 20, 'comes admired': 15, 'admired inmates': 5, 'inmates including': 27, 'including older': 25, 'older prisoner': 43, 'prisoner named': 48, 'named red': 39, 'red integrity': 52, 'integrity unquenchable': 29, 'unquenchable sense': 62, 'sense hope': 54}
71

In [108]:
cv = CountVectorizer(ngram_range = (2,3))
bow = cv.fit_transform(df['overview'][:1])
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'imprisoned 1940s': 22, '1940s double': 0, 'double murder': 16, 'murder wife': 36, 'wife lover': 67, 'lover upstanding': 34, 'upstanding banker': 63, 'banker andy': 10, 'andy dufresne': 8, 'dufresne begins': 18, 'begins new': 12, 'new life': 40, 'life shawshank': 30, 'shawshank prison': 55, 'prison puts': 46, 'puts accounting': 50, 'accounting skills': 2, 'skills work': 57, 'work amoral': 69, 'amoral warden': 6, 'warden long': 65, 'long stretch': 32, 'stretch prison': 59, 'prison dufresne': 44, 'dufresne comes': 20, 'comes admired': 14, 'admired inmates': 4, 'inmates including': 26, 'including older': 24, 'older prisoner': 42, 'prisoner named': 48, 'named red': 38, 'red integrity': 52, 'integrity unquenchable': 28, 'unquenchable sense': 61, 'sense hope': 54, 'imprisoned 1940s double': 23, '1940s double murder': 1, 'double murder wife': 17, 'murder wife lover': 37, 'wife lover upstanding': 68, 'lover upstanding banker': 35, 'upstanding banker andy': 64, 'banker andy dufresne': 11, 'andy dufresne begins': 9, 'dufresne begins new': 19, 'begins new life': 13, 'new life shawshank': 41, 'life shawshank prison': 31, 'shawshank prison puts': 56, 'prison puts accounting': 47, 'puts accounting skills': 51, 'accounting skills work': 3, 'skills work amoral': 58, 'work amoral warden': 70, 'amoral warden long': 7, 'warden long stretch': 66, 'long stretch prison': 33, 'stretch prison dufresne': 60, 'prison dufresne comes': 45, 'dufresne comes admired': 21, 'comes admired inmates': 15, 'admired inmates including': 5, 'inmates including older': 27, 'including older prisoner': 25, 'older prisoner named': 43, 'prisoner named red': 49, 'named red integrity': 39, 'red integrity unquenchable': 53, 'integrity unquenchable sense': 29, 'unquenchable sense hope': 62}
71

## **Tf-Idf Vectorization**

In [ ]:
from sklearn.feature_extraction import TfIdfVec
tfidf = Tfidfvectorizer()
tfidf.fit_transform(df['overview']).toarray()

ImportError: cannot import name 'Tfidfvectorizer' from 'sklearn.feature_extraction' (/home/om-codex/ml/ml_env/lib64/python3.11/site-packages/sklearn/feature_extraction/__init__.py)